// Auto-generated by RAudioGenerator
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
        public static AudioClip cin;
        public static AudioClip Clic05;
        public static AudioClip damage_magic;
        public static AudioClip DuckSound;
        public static AudioClip f;
        public static AudioClip HighVoice;
        public static AudioClip j;
        public static AudioClip k;
        public static AudioClip menu_click;
        public static AudioClip misc_menu;
        public static AudioClip misc_menu_2;
        public static AudioClip misc_menu_4;
        public static AudioClip misc_sound;
        public static AudioClip MouseClicked;
        public static AudioClip MouseInButton;
        public static AudioClip negative;
        public static AudioClip negative_2;
        public static AudioClip o;
        public static AudioClip PanelIn;
        public static AudioClip PanelOut;
        public static AudioClip pin;
        public static AudioClip poo;
        public static AudioClip positive;
        public static AudioClip psi;
        public static AudioClip s;
        public static AudioClip save;
        public static AudioClip sfx_woosh;
        public static AudioClip sharp_echo;
        public static AudioClip Upper01;
        public static AudioClip win_magic;
        public static AudioClip Wrong_Error;
        public static AudioClip y;
        public static AudioClip AddShield;
        public static AudioClip click;
        public static AudioClip click_2;
        public static AudioClip damage;
        public static AudioClip DestroyShield;
        public static AudioClip Louse;
        public static AudioClip Meow;
        public static AudioClip NewMainMenu;
        public static AudioClip part;
        public static AudioClip pop1;
        public static AudioClip pop2;
        public static AudioClip pop3;
        public static AudioClip Sound_91275600_1637863823;
        public static AudioClip SpawnPiece;
        public static AudioClip squeakEcho;
        public static AudioClip tutorial;
        public static AudioClip TypingSound;
        public static AudioClip vriiis;
    }

    public static void InitAudio()
    {
        Audio.cin = Resources.Load<AudioClip>("Audio/Bank/cin");
        Audio.Clic05 = Resources.Load<AudioClip>("Audio/Bank/Clic05");
        Audio.damage_magic = Resources.Load<AudioClip>("Audio/Bank/damage_magic");
        Audio.DuckSound = Resources.Load<AudioClip>("Audio/Bank/DuckSound");
        Audio.f = Resources.Load<AudioClip>("Audio/Bank/f");
        Audio.HighVoice = Resources.Load<AudioClip>("Audio/Bank/HighVoice");
        Audio.j = Resources.Load<AudioClip>("Audio/Bank/j");
        Audio.k = Resources.Load<AudioClip>("Audio/Bank/k");
        Audio.menu_click = Resources.Load<AudioClip>("Audio/Bank/menu_click");
        Audio.misc_menu = Resources.Load<AudioClip>("Audio/Bank/misc_menu");
        Audio.misc_menu_2 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_2");
        Audio.misc_menu_4 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_4");
        Audio.misc_sound = Resources.Load<AudioClip>("Audio/Bank/misc_sound");
        Audio.MouseClicked = Resources.Load<AudioClip>("Audio/Bank/MouseClicked");
        Audio.MouseInButton = Resources.Load<AudioClip>("Audio/Bank/MouseInButton");
        Audio.negative = Resources.Load<AudioClip>("Audio/Bank/negative");
        Audio.negative_2 = Resources.Load<AudioClip>("Audio/Bank/negative_2");
        Audio.o = Resources.Load<AudioClip>("Audio/Bank/o");
        Audio.PanelIn = Resources.Load<AudioClip>("Audio/Bank/PanelIn");
        Audio.PanelOut = Resources.Load<AudioClip>("Audio/Bank/PanelOut");
        Audio.pin = Resources.Load<AudioClip>("Audio/Bank/pin");
        Audio.poo = Resources.Load<AudioClip>("Audio/Bank/poo");
        Audio.positive = Resources.Load<AudioClip>("Audio/Bank/positive");
        Audio.psi = Resources.Load<AudioClip>("Audio/Bank/psi");
        Audio.s = Resources.Load<AudioClip>("Audio/Bank/s");
        Audio.save = Resources.Load<AudioClip>("Audio/Bank/save");
        Audio.sfx_woosh = Resources.Load<AudioClip>("Audio/Bank/sfx_woosh");
        Audio.sharp_echo = Resources.Load<AudioClip>("Audio/Bank/sharp_echo");
        Audio.Upper01 = Resources.Load<AudioClip>("Audio/Bank/Upper01");
        Audio.win_magic = Resources.Load<AudioClip>("Audio/Bank/win_magic");
        Audio.Wrong_Error = Resources.Load<AudioClip>("Audio/Bank/Wrong Error");
        Audio.y = Resources.Load<AudioClip>("Audio/Bank/y");
        Audio.AddShield = Resources.Load<AudioClip>("Audio/Use/AddShield");
        Audio.click = Resources.Load<AudioClip>("Audio/Use/click");
        Audio.click_2 = Resources.Load<AudioClip>("Audio/Use/click_2");
        Audio.damage = Resources.Load<AudioClip>("Audio/Use/damage");
        Audio.DestroyShield = Resources.Load<AudioClip>("Audio/Use/DestroyShield");
        Audio.Louse = Resources.Load<AudioClip>("Audio/Use/Louse");
        Audio.Meow = Resources.Load<AudioClip>("Audio/Use/Meow");
        Audio.NewMainMenu = Resources.Load<AudioClip>("Audio/Use/NewMainMenu");
        Audio.part = Resources.Load<AudioClip>("Audio/Use/part");
        Audio.pop1 = Resources.Load<AudioClip>("Audio/Use/pop1");
        Audio.pop2 = Resources.Load<AudioClip>("Audio/Use/pop2");
        Audio.pop3 = Resources.Load<AudioClip>("Audio/Use/pop3");
        Audio.Sound_91275600_1637863823 = Resources.Load<AudioClip>("Audio/Use/Sound_91275600 1637863823");
        Audio.SpawnPiece = Resources.Load<AudioClip>("Audio/Use/SpawnPiece");
        Audio.squeakEcho = Resources.Load<AudioClip>("Audio/Use/squeakEcho");
        Audio.tutorial = Resources.Load<AudioClip>("Audio/Use/tutorial");
        Audio.TypingSound = Resources.Load<AudioClip>("Audio/Use/TypingSound");
        Audio.vriiis = Resources.Load<AudioClip>("Audio/Use/vriiis");
    }
}
