// Auto-generated by RAudioGenerator
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
        public static AudioClip ApplySound;
        public static AudioClip ArtefactSound;
        public static AudioClip BatteryColisionSound;
        public static AudioClip batteryRunOut;
        public static AudioClip batterySet;
        public static AudioClip boom;
        public static AudioClip CasseteSound;
        public static AudioClip DuckBaimit;
        public static AudioClip DuckSound;
        public static AudioClip factorybg;
        public static AudioClip Horror;
        public static AudioClip LevelDown;
        public static AudioClip MachineSpeak;
        public static AudioClip MachineStarted;
        public static AudioClip MachineStopped;
        public static AudioClip MainGameMusic;
        public static AudioClip MainMenu;
        public static AudioClip MultMusic;
        public static AudioClip OpenCover;
        public static AudioClip OpenDoor;
        public static AudioClip PipeOutNewObject;
        public static AudioClip ResistorSound;
        public static AudioClip ScarySound;
        public static AudioClip ThrowOut;
        public static AudioClip Clic05;
        public static AudioClip click;
        public static AudioClip click_2;
        public static AudioClip load;
        public static AudioClip misc_menu;
        public static AudioClip misc_menu_2;
        public static AudioClip misc_menu_4;
        public static AudioClip misc_sound;
        public static AudioClip MouseClicked;
        public static AudioClip MouseInButton;
        public static AudioClip negative;
        public static AudioClip negative_2;
        public static AudioClip PanelIn;
        public static AudioClip PanelOut;
        public static AudioClip part;
        public static AudioClip positive;
        public static AudioClip save;
        public static AudioClip sharp_echo;
        public static AudioClip Upper01;
        public static AudioClip Wrong_Error;
    }

    public static void InitAudio()
    {
        Audio.ApplySound = Resources.Load<AudioClip>("Audio/ApplySound");
        Audio.ArtefactSound = Resources.Load<AudioClip>("Audio/ArtefactSound");
        Audio.BatteryColisionSound = Resources.Load<AudioClip>("Audio/BatteryColisionSound");
        Audio.batteryRunOut = Resources.Load<AudioClip>("Audio/batteryRunOut");
        Audio.batterySet = Resources.Load<AudioClip>("Audio/batterySet");
        Audio.boom = Resources.Load<AudioClip>("Audio/boom");
        Audio.CasseteSound = Resources.Load<AudioClip>("Audio/CasseteSound");
        Audio.DuckBaimit = Resources.Load<AudioClip>("Audio/DuckBaimit");
        Audio.DuckSound = Resources.Load<AudioClip>("Audio/DuckSound");
        Audio.factorybg = Resources.Load<AudioClip>("Audio/factorybg");
        Audio.Horror = Resources.Load<AudioClip>("Audio/Horror");
        Audio.LevelDown = Resources.Load<AudioClip>("Audio/LevelDown");
        Audio.MachineSpeak = Resources.Load<AudioClip>("Audio/MachineSpeak");
        Audio.MachineStarted = Resources.Load<AudioClip>("Audio/MachineStarted");
        Audio.MachineStopped = Resources.Load<AudioClip>("Audio/MachineStopped");
        Audio.MainGameMusic = Resources.Load<AudioClip>("Audio/MainGameMusic");
        Audio.MainMenu = Resources.Load<AudioClip>("Audio/MainMenu");
        Audio.MultMusic = Resources.Load<AudioClip>("Audio/MultMusic");
        Audio.OpenCover = Resources.Load<AudioClip>("Audio/OpenCover");
        Audio.OpenDoor = Resources.Load<AudioClip>("Audio/OpenDoor");
        Audio.PipeOutNewObject = Resources.Load<AudioClip>("Audio/PipeOutNewObject");
        Audio.ResistorSound = Resources.Load<AudioClip>("Audio/ResistorSound");
        Audio.ScarySound = Resources.Load<AudioClip>("Audio/ScarySound");
        Audio.ThrowOut = Resources.Load<AudioClip>("Audio/ThrowOut");
        Audio.Clic05 = Resources.Load<AudioClip>("Audio/Bank/Clic05");
        Audio.click = Resources.Load<AudioClip>("Audio/Bank/click");
        Audio.click_2 = Resources.Load<AudioClip>("Audio/Bank/click_2");
        Audio.load = Resources.Load<AudioClip>("Audio/Bank/load");
        Audio.misc_menu = Resources.Load<AudioClip>("Audio/Bank/misc_menu");
        Audio.misc_menu_2 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_2");
        Audio.misc_menu_4 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_4");
        Audio.misc_sound = Resources.Load<AudioClip>("Audio/Bank/misc_sound");
        Audio.MouseClicked = Resources.Load<AudioClip>("Audio/Bank/MouseClicked");
        Audio.MouseInButton = Resources.Load<AudioClip>("Audio/Bank/MouseInButton");
        Audio.negative = Resources.Load<AudioClip>("Audio/Bank/negative");
        Audio.negative_2 = Resources.Load<AudioClip>("Audio/Bank/negative_2");
        Audio.PanelIn = Resources.Load<AudioClip>("Audio/Bank/PanelIn");
        Audio.PanelOut = Resources.Load<AudioClip>("Audio/Bank/PanelOut");
        Audio.part = Resources.Load<AudioClip>("Audio/Bank/part");
        Audio.positive = Resources.Load<AudioClip>("Audio/Bank/positive");
        Audio.save = Resources.Load<AudioClip>("Audio/Bank/save");
        Audio.sharp_echo = Resources.Load<AudioClip>("Audio/Bank/sharp_echo");
        Audio.Upper01 = Resources.Load<AudioClip>("Audio/Bank/Upper01");
        Audio.Wrong_Error = Resources.Load<AudioClip>("Audio/Bank/Wrong Error");
    }
}
